### PR TITLE
Openlane_ubuntuOS_ img

### PR DESCRIPTION
**Pull request by mahmoodulhassan-lm**
1- swift:5.3.2-bionic is used as the base OS to support [FAULT](https://github.com/Cloud-V/Fault) at a later stage.
2- Perl 5.16.3 is installed to support perl files. Perls files. i.e. [libtrim](https://github.com/efabless/openlane/blob/master/scripts/libtrim.pl), [cts_simple](https://github.com/efabless/openlane/blob/master/scripts/cts/cts_simple.pl)  and [analyze](https://github.com/efabless/openlane/blob/master/scripts/synth_exp/analyze.pl) should be updated to be supported by the latest version of Perl.
3- K-layout is excluded for now and will be added at later stage.
4- Successfully Tested with rc6 branch.
5- Please exclude dependencies related to K-layout for a clear run on develop branch.

### CODE REVIEW

**Comment by ax3ghazy** [comment]
Please rebase this on the `develop` branch (start applying your fixes on top of the latest commit on `develop`), and set `develop` as the target merge branch.

**Comment by mahmoodulhassan-lm** [comment]
> Please rebase this on the `develop` branch (start applying your fixes on top of the latest commit on `develop`), and set `develop` as the target merge branch.
I have tested this on rc6 branch and the basic test was successfull. The problem which I think is with the k-layout which is not included in it and by observing the log generated by Travis-Cl , basic test failed while trying to run k-layout. Should I fix this bug by according to the guidelines mentioned above or is there any possibility to run this with rc6?

**Comment by agorararmard** [comment]
@mahmoodulhassan-lm: Thanks for your PR! 

In general, when a version is out, it's out. We don't make changes to old versions; instead, we release new ones (as an extension of these older versions). So, since `rc6` is on the master branch, all changes should be done to `rc7`, which is `develop`. With that said, the Klayout version in the repo is centos7 specific. Still, you'll need the ubuntu deb for it to work in an ubuntu docker, i.e., https://www.klayout.org/downloads/Ubuntu-20/klayout_0.26.9-1_amd64.deb, and note that converting the top-level docker to Ubuntu 20 and leaving the tools in centos7 won't be good, so all the tools should be migrated as well, which brings me to the next point: #161. Also, no need to have swift at the moment since Fault is not yet integrated + when it's integrated it will be treated as one of the tools and has its own docker unless we decide to go with #161, which won't happen before rc8.

Thanks again!

**Comment by mahmoodulhassan-lm** [comment]
> @mahmoodulhassan-lm: Thanks for your PR!
> 
> In general, when a version is out, it's out. We don't make changes to old versions; instead, we release new ones (as an extension of these older versions). So, since `rc6` is on the master branch, all changes should be done to `rc7`, which is `develop`. With that said, the Klayout version in the repo is centos7 specific. Still, you'll need the ubuntu deb for it to work in an ubuntu docker, i.e., https://www.klayout.org/downloads/Ubuntu-20/klayout_0.26.9-1_amd64.deb, and note that converting the top-level docker to Ubuntu 20 and leaving the tools in centos7 won't be good, so all the tools should be migrated as well, which brings me to the next point: #161. Also, no need to have swift at the moment since Fault is not yet integrated + when it's integrated it will be treated as one of the tools and has its own docker unless we decide to go with #161, which won't happen before rc8.
> 
> Thanks again!

@agorararmard : I am thankful for the input regarding PR. Sure, I have already started migrating tools to UbuntuOS and will be working on it from now on according to the provided guidelines.

**Comment by donn** [comment]
Stale/Swift supports Centos. Closing this.

**Pull request closed without merging**
