### PR TITLE
Apply CELL_PAD to replace

### PR DESCRIPTION
**Pull request by antonblanchard**
replace has a somewhat recent option to specify padding.

### CODE REVIEW

**Comment by antonblanchard** [comment]
I notice a few other differences vs the openroad regression tests:

openroad applies a left and right pad, and openlane applies only one (left for cts, right otherwise). This might make a small improvement to routability I think. Could we apply CELL_PAD/2 left and right?

openroad also applies 2x padding in global placement vs detailed placement, I'm not sure why.

**Comment by antonblanchard** [comment]
I wonder if this will cause some working configurations to fail during global placement

**Comment by antonblanchard** [comment]
It does seem to cause previously passing configurations to fail.

**Comment by agorararmard** [comment]
@antonblanchard: We set these values with experimentation over the test set we provide in the repo: https://github.com/efabless/openlane/tree/master/designs I don't think it will make a huge difference if the padding is to the left or to the right or divided over both. However, if you have a test case that proves the significant difference we'll be happy to reconsider.

It seems that replace's cell padding didn't work well with the current designs and flow setup (maybe it needs to be 2x as you said?). Perhaps we can look into this later. But, for now, I will not be able to merge this PR (check the CI for more details).

**Comment by antonblanchard** [comment]
Agreed, lets close it for now and we can try tuning it sometime later.

**Pull request closed without merging**
