### PR TITLE
write a post techmap dot file

### PR DESCRIPTION
**Pull request by mattvenn**
this creates a useful dot file to examine the techmap process. It's done before too much optimisation so the results are  understandable for small designs.

### CODE REVIEW

**Comment by donn** [comment]
Sorry to bother you Matt, but can you rebase? Just so the CI can run on this.

**Comment by mattvenn** [comment]
Hi Donn,
happy to do this but I don't really know how.
Would it be easier to just make a new PR on main?

**Comment by donn** [comment]
On the develop branch, preferably. We're freezing master for OpenMPW 2.

**Comment by donn** [comment]
Superseded by #322. Closed.

**Pull request closed without merging**
