### PR TITLE
Fixes for mac

### PR DESCRIPTION
**Pull request by robtaylor**
Some tweaks for getting Openlane start of day experience better on my macbook..

### CODE REVIEW

**Comment by smunaut** [comment]
Why do all theses tcl file neet the `x` bit set anyway ?

I run natively (not with docker), never changes the `x` bit on those and I never had any issues ... AFAIK you never call theses directly so it's not needed.

**Comment by agorararmard** [comment]
@robtaylor: Thank you very much for your Pull Request. Could you rebase that to the develop branch in order for us to go forward with it?
https://github.com/efabless/openlane/blob/master/CONTRIBUTING.md

**Comment by robtaylor** [comment]
@agorararmard Thanks, i'd missed that. rebased against develop now.

**Review by agorararmard — APPROVED** [review]

**Comment by robtaylor** [comment]
Thank you Amr!

**Pull request merged**
